In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("student_data.csv")
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [7]:
G1 = df["G1"]
G1

0       5
1       5
2       7
3      15
4       6
       ..
390     9
391    14
392    10
393    11
394     8
Name: G1, Length: 395, dtype: int64

In [8]:
G2 = df['G2']
G2

0       6
1       5
2       8
3      14
4      10
       ..
390     9
391    16
392     8
393    12
394     9
Name: G2, Length: 395, dtype: int64

In [3]:
df["average_grade"] = (df["G1"] + df["G2"] + df["G3"]) / 3

In [4]:
df["total_alcohol"] = df["Dalc"] + df["Walc"]

In [13]:
def age_group(age):
    if age <= 16:
        return "Young"
    elif age <= 18:
        return "Teen"
    else:
        return "Adult"

In [14]:
df["age_group"] = df["age"].apply(age_group)
df['age_group']

0       Teen
1       Teen
2      Young
3      Young
4      Young
       ...
390    Adult
391     Teen
392    Adult
393     Teen
394    Adult
Name: age_group, Length: 395, dtype: str

In [10]:
def performance(score):
    if score >= 16:
        return "Excellent"
    elif score >= 12:
        return "Good"
    elif score >= 8:
        return "Average"
    else:
        return "Poor"

In [12]:
df["performance"] = df["G3"].apply(performance)
df["performance"]

0           Poor
1           Poor
2        Average
3           Good
4        Average
         ...
390      Average
391    Excellent
392         Poor
393      Average
394      Average
Name: performance, Length: 395, dtype: str

In [15]:
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,Walc,health,absences,G1,G2,G3,average_grade,total_alcohol,age_group,performance
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,1,3,6,5,6,6,5.666667,2,Teen,Poor
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,1,3,4,5,5,6,5.333333,2,Teen,Poor
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,3,3,10,7,8,10,8.333333,5,Young,Average
3,GP,F,15,U,GT3,T,4,2,health,services,...,1,5,2,15,14,15,14.666667,2,Young,Good
4,GP,F,16,U,GT3,T,3,3,other,other,...,2,5,4,6,10,10,8.666667,3,Young,Average
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,4,11,9,9,9,9.000000,9,Adult,Average
391,MS,M,17,U,LE3,T,3,1,services,services,...,4,2,3,14,16,16,15.333333,7,Teen,Excellent
392,MS,M,21,R,GT3,T,1,1,other,other,...,3,3,3,10,8,7,8.333333,6,Adult,Poor
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,5,0,11,12,10,11.000000,7,Teen,Average
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,5,5,8,9,9,8.666667,6,Adult,Average