In [1]:
import sqlite3
import pandas as pd

In [2]:
connectionDB = sqlite3.connect("sample.db")
cursor = connectionDB.cursor()

In [3]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS employees (
    id INTEGER PRIMARY KEY,
    name TEXT,
    department TEXT,
    salary REAL
)
""")

In [4]:
employees = [
    (1, "Alice", "HR", 50000),
    (2, "Bob", "IT", 65000),
    (3, "Charlie", "Finance", 55000),
    (4, "David", "Marketing", 48000),
    (5, "Emma", "IT", 70000)
]

In [5]:

cursor.executemany(
    "INSERT OR REPLACE INTO employees VALUES (?, ?, ?, ?)",
    employees
)

In [6]:
connectionDB.commit()

In [7]:
df = pd.read_sql_query("SELECT * FROM employees", connectionDB)

In [8]:
df

   id     name department   salary
0   1    Alice         HR  50000.0
1   2      Bob         IT  65000.0
2   3  Charlie    Finance  55000.0
3   4    David  Marketing  48000.0
4   5     Emma         IT  70000.0

In [9]:
df.columns

Index(['id', 'name', 'department', 'salary'], dtype='str')

In [10]:
df.shape

(5, 4)

In [11]:
df.head()

   id     name department   salary
0   1    Alice         HR  50000.0
1   2      Bob         IT  65000.0
2   3  Charlie    Finance  55000.0
3   4    David  Marketing  48000.0
4   5     Emma         IT  70000.0

In [12]:
connectionDB.close()